apiVersion: apps/v1
kind: Deployment
metadata:
  name: &service-name net-tools
  labels: &labels
    app: *service-name
spec:
  minReadySeconds: 1
  selector:
    matchLabels: *labels
  replicas: 1
  revisionHistoryLimit: 10
  template: 
    metadata:
      labels: *labels
    spec:
      containers:
      - name: *service-name
        image: chuckautomates/net-tools:v0.0.0
        #command: ["tail -f /dev/null"]
